### ISSUE TITLE
Remove the libc dependency

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/tree-sitter-core#12]
Functions to replace:
- [ ] Remove fputs() #10 
- [ ] Remove fputc() #9 
- [x] Remove __assert_fail() #8
- [ ] Remove clock_gettime() #7
- [ ] Remove iswspace()/iswalnum() #6
- [x] Remove __ctype_b_loc() #5 
- [x] Remove exit() #4 
- [ ] Remove fprintf() #3 
- [ ] Remove fdopen()/fclose() #2 
- [ ] Remove snprintf() #1
